title: 'Alejandro Escalante'
author:
  name: 'Alejandro Escalante'
description: 'una pagina personal'
other:
  home: 'https://alex-esc.github.io/personal-website-tests/'
  docs: 'https://alex-esc.github.io/personal-website-tests/docs/document_index.html'
  about: 'https://alex-esc.github.io/personal-website-tests/pages/about.html'
  language: 'https://alex-esc.github.io/personal-website-tests/language.html'

path: '/personal-website-tests'
url:  'https://alex-esc.github.io/personal-website-tests/'

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false


plugins:
  - jemoji