title: 'Alejandro Escalante'
author:
  name: 'Alejandro Escalante'
description: 'una pagina personal'

 plugins:
  - jemoji
path: '/personal-website-tests'
url:  'https://alex-esc.github.io/personal-website-tests/'

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false